### ISSUE TITLE
Flatpak broken

### ISSUE THREAD

**Issue by pizzadude** [hongquan/CoBang#13]
After latest update the flatpak is broken.
Terminal log:
```
flatpak run vn.hoabinh.quan.CoBang
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/lib/python3.7/site-packages/cobang/__main__.py", line 17, in <module>
    from .app import CoBangApplication
  File "/app/lib/python3.7/site-packages/cobang/app.py", line 44, in <module>
    from . import ui
ImportError: cannot import name 'ui' from 'cobang' (/app/lib/python3.7/site-packages/cobang/__init__.py)
```

**Comment by hongquan** [comment]
Thank you @pizzadude for reporting. I will fix.

**Comment by hongquan** [comment]
The Flatpak package is fixed, but by some reason, the new version does not appear in FlatHub yet.

**Comment by pizzadude** [comment]
It is fixed now. Thank you.
