### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Fxsch** [hongquan/CoBang#52]
I'm running Arch Linux and I've installed CoBang through the AUR.

When I start CoBang it instantly crashes. This is what the terminal shows me;

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/usr/lib/python3.10/site-packages/cobang/__init__.py", line 5, in <module>
    from single_version import get_version
ModuleNotFoundError: No module named 'single_version' 
```

**Comment by hongquan** [comment]
Thanks for reporting, @Fxsch 

@yochananmarqos is the maintaner of ArchLinux package. Please help!

**Comment by yochananmarqos** [comment]
Every time there's a major Python update like 3.10, one must rebuild their Python packages from the AUR. See this post for more info: https://www.reddit.com/r/archlinux/comments/rf6c84/psa_python_310_is_in_core_rebuild_your_aur/
