### ISSUE TITLE
CoBang doesn't work under Wayland

### ISSUE THREAD

**Issue by ibahnasy** [hongquan/CoBang#55]
Ubuntu 22.04 with Wayland.
`Gdk-Message: 13:07:48.828: Error flushing display: Protocol error`

**Comment by ibahnasy** [comment]
@hongquan It's hybrid laptop, (intel + nvidia Geforce MX450).

**Comment by Enricone27** [comment]
Same error here with flatpak...
`/app/bin/cobang: Zeile 9:     3 Speicherzugriffsfehler  (Speicherabzug geschrieben) /usr/bin/python3 -m cobang "$@"`
I deactivated Wayland Socket in Flatseal and now it works...

**Comment by hongquan** [comment]
Hi, @Enricone27 Is this still an issue with v1.5 or v1.6?

**Comment by ibahnasy** [comment]
```
$ cobang 
Traceback (most recent call last):
  File "/usr/bin/cobang", line 45, in <module>
    from cobang import app
  File "/usr/share/cobang/cobang/app.py", line 30, in <module>
    gi.require_version('Xdp', '1.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 122, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Xdp not available
```

**Comment by hongquan** [comment]
Hi @ibahnasy 
Could you try installing `gir1.2-xdp-1.0` package and try again? I missed this package in the dependency list.

**Comment by ibahnasy** [comment]
This one `gir1.2-xdpgtk4-1.0` was also needed, now the app starts.

**Comment by hongquan** [comment]
Thank you.
