### ISSUE TITLE
Backend 'poetry.masonry.api' is not available.

### ISSUE THREAD

**Issue by yurivict** [hongquan/CoBang#65]
Build fails:
```
===>  Building for py39-cobang-0.9.10
* Getting build dependencies for wheel...

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pep517/wrappers.py", line 319, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pep517.wrappers.BackendUnavailable: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pep517/in_process/_in_process.py", line 77, in _build_backend
    obj = import_module(mod_path)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'poetry.masonry'

ERROR Backend 'poetry.masonry.api' is not available.
*** Error code 1

Stop.
make: stopped in /usr/ports/sysutils/cobang
```

poetry-1.3.2 (the latest version) is installed, but it only provides one executable 'poetry'.

Is there a mistake in pyproject.toml?

Version: 0.9.10
Python-3.9
FreeBSD 13.1

**Comment by hongquan** [comment]
Yes, the pyproject.toml is outdated. I will update.

**Comment by hongquan** [comment]
@yurivict The "main" branch already has updated pyproject.toml file. Do you need me to make a new version (a Git tag) for this update?
